version: '3.8'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ticket-platform
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data